set -g fish_color_normal c9d1d9
set -g fish_color_command 79c0ff
set -g fish_color_param c9d1d9
set -g fish_color_quote a5d6ff
set -g fish_color_redirection d2a8ff
set -g fish_color_end 7ee787
set -g fish_color_error ff7b72
set -g fish_color_operator e3b341
set -g fish_color_escape a5d6ff
set -g fish_color_comment 6e7681
set -g fish_color_autosuggestion 6e7681
set -g fish_color_cwd 79c0ff
set -g fish_color_cwd_root ff7b72
set -g fish_color_user c9d1d9
set -g fish_color_host 6e7681
set -g fish_color_status ff7b72
set -g fish_color_valid_path --underline
set -g fish_color_search_match --background=264f78
set -g fish_color_selection --background=264f78

set -g fish_pager_color_completion c9d1d9
set -g fish_pager_color_description 6e7681
set -g fish_pager_color_prefix 79c0ff
set -g fish_pager_color_progress 6e7681
set -g fish_pager_color_selected_background --background=264f78
