services:
  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: local1234
      MINIO_ROOT_PASSWORD: local1234
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: server /data --console-address ":9001"
